#pragma once
#include <IL/OMX_Core.h>

OMX_API OMX_ERRORTYPE OMX_APIENTRY OMXDRM_GetHandle(
    OMX_OUT OMX_HANDLETYPE* pHandle,
    OMX_IN  OMX_STRING cComponentName,
    OMX_IN  OMX_PTR pAppData,
    OMX_IN  OMX_CALLBACKTYPE* pCallBacks);

OMX_API OMX_ERRORTYPE OMX_APIENTRY OMXDRM_FreeHandle(
    OMX_IN  OMX_HANDLETYPE hComponent);
